import React from 'react';
import {
  CheckCircle2,
  Download,
  FileText,
  Trash2,
} from 'lucide-react';

import PageHeader from '../components/PageHeader';
import { useIncidents } from '../context/IncidentContext';

export default function Reports() {
  const {
    incidents,
    acknowledgeIncident,
    acknowledgeAll,
    clearIncidents,
  } = useIncidents();

  const exportCSV = () => {
    const headers = [
      'ID',
      'Title',
      'Object',
      'Confidence',
      'Severity',
      'Location',
      'Source',
      'Status',
    ];

    const rows = incidents.map((item) => [
      item.id,
      item.title,
      item.objectName,
      item.confidence,
      item.severity,
      item.location,
      item.source,
      item.status,
    ]);

    const csv = [headers, ...rows]
      .map((row) =>
        row
          .map((value) =>
            `"${String(value).replaceAll('"', '""')}"`
          )
          .join(',')
      )
      .join('\n');

    const link = document.createElement('a');

    link.href = URL.createObjectURL(
      new Blob([csv], { type: 'text/csv' })
    );

    link.download = 'railguard-incidents.csv';
    link.click();

    URL.revokeObjectURL(link.href);
  };

  return (
    <>
      <PageHeader
        title="Incident Reports"
        subtitle="CRUD records generated by camera detection and safety tests."
      >
        <div className="action-row">
          <button
            className="secondary-btn"
            onClick={exportCSV}
          >
            <Download size={17} />
            Export CSV
          </button>

          <button
            className="secondary-btn"
            onClick={acknowledgeAll}
          >
            <CheckCircle2 size={17} />
            Acknowledge All
          </button>

          <button
            className="danger-btn"
            onClick={clearIncidents}
          >
            <Trash2 size={16} />
            Clear Demo Data
          </button>
        </div>
      </PageHeader>

      <div className="report-table panel">
        <div className="table-head">
          <span>Severity</span>
          <span>Event</span>
          <span>Confidence</span>
          <span>Source</span>
          <span>Location</span>
          <span>Status</span>
        </div>

        {incidents.length ? (
          incidents.map((incident) => (
            <div
              className="table-row"
              key={incident.id}
            >
              <span>
                <span
                  className={`severity-badge ${incident.severity}`}
                >
                  {incident.severity.toUpperCase()}
                </span>
              </span>

              <span>
                <strong>{incident.title}</strong>
                <small>
                  {incident.objectName} • {incident.id}
                </small>
              </span>

              <span>{incident.confidence}%</span>
              <span>{incident.source}</span>
              <span>{incident.location}</span>

              <span>
                {incident.status === 'Open' ? (
                  <button
                    className="mini-btn"
                    onClick={() =>
                      acknowledgeIncident(incident.id)
                    }
                  >
                    Acknowledge
                  </button>
                ) : (
                  <span className="ack">
                    Acknowledged
                  </span>
                )}
              </span>
            </div>
          ))
        ) : (
          <div className="table-empty">
            <FileText size={30} />
            <strong>No reports yet</strong>
            <span>Run a Safety Test to create one.</span>
          </div>
        )}
      </div>
    </>
  );
}
